### ISSUE TITLE
Error with inspiredminds/contao-wowjs

### ISSUE THREAD

**Issue by sdahlmann** [delirius/contao-structure-elements#1]
If I use the Contao Structure Element and the extension "inspiredminds/contao-wowjs" is installed at the same time, I get the following error message when creating the Start-Structure Element as a DIV element: "An exception occurred while executing a query: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'wowjsOffset' at row 1". Question: Is there an incompatibility with the structure element and can you fix it when you have a chance?

**Comment by delirius** [comment]
Fixed bug database insert
